export const environment = {
  production: false,
  Razorpay_test_key:'rzp_test_GxaJhvoS78ZpIz',
  Razorpay_live_key:'rzp_test_Z6PoT6HRL71TiC',

  // Testing url
  // media_url: 'https://vlp.thestorywallcafe.com',
  media_url: 'https://vlp-prod.s3.amazonaws.com',
  live_url:'https://vlp.thestorywallcafe.com/api-vlp',
  socket_url:'projectacedevelop.thestorywallcafe.com',

  // UAT url
  // media_url: 'https://vlpuat.thestorywallcafe.com',
  // live_url:'https://vlpuat.thestorywallcafe.com/api-vlp',
  // socket_url:'projectacedevelop.thestorywallcafe.com',


  // Staging URL
  // media_url: 'https://vlp-prod.s3.amazonaws.com',
  // live_url:'https://staging.vlpworkflow.com/api-vlp',
  // socket_url:'projectacedevelop.thestorywallcafe.com',

  //  vlp Auth
  login:`login`,
  forgot_password:`forgot-password`,
  verify_otp:`verify-otp`,
  set_new_password:`set-new-password`,
  change_password:`change-password`,
  // vlp settings
user:`user`,
settings_country: `country`,
settings_source: `source`,
settings_status_group: `status-group`,
settings_leave_type: `leave_type`,
employee_leave_type: `employee_leaves`,
settings_job_status: `job-status`,
settings_job_type: `job-type`,
settings_service: `service`,
settings_designation:`designation`,
settings_roles:`roles`,
settings_periodicty:'periodicity',
settings_period:'period',
roles_access:`roles-access`,
role_designation_access:`designation-access`,
user_access:`user-access`,
// vlp Templates
templates:`templates`,
// vlp Employee
employee:`user`,
director_data:`employees`,
change_manager:`change-manager`,
// vlp company policy
company_policy:`company-policy`,
// vlp clients
clients:'clients',
all_clients:`all-clients`,
clients_details:'clients-details',

job_details:'job-details',
jobs_percetage:'jobs-percetage',
clients_group:'group',
end_clients:'end-clients',
end_client_jobs:`end-client-jobs`,
// jobs
jobs:`jobs`,
only_jobs:`only-jobs`,
all_jobs:`all-jobs`,
jobs_search:`jobs-search`,
jobs_kpi:'kpi',
// timesheet
 timesheet_summary:`timesheet-summary`,
 timesheet_reports:`timesheet-reports`,
vlp_timesheets:`timesheet`,
timesheet_non_productivity: `timesheet-non-productivity`,
submit_weekly_timesheet:`submit-weekly-timesheet`,
client_invoice:'client-invoice',
invoice_details:'invoice-details',
view_invoice:'client-invoices',
job_reports:'job-reports',
productivity_reports:'productivity-reports',
upload_assessment:'upload-assessment',
over_all_productivity_reports:'over-all-productivity-reports',
download_excel :'download-excel',
get_primary_employees: `get-primary-employees`,
non_productivity:`timesheet-non-productivity`,
//  leave related API end points
work_calendar:`work_calender`,
holiday_calendar:`holiday_calendar`,
apply_leaves: `apply_leave`,
my_leaves:`my-leaves-combined-comp-off-and-all`,
comp_off_grant: `new-comp-off`,
employees_leave:`employee_leaves`,
revoke_my_leave:`revoke-my-leave`,
approve_compoff:`revoke-my-comp-of`,
leave_status:`get-leave-status`,
period_values: `get-period-values`,
all_emp_custom_balance:`customize-balance`,
leave_transaction_report: `leave-transaction-report`,
leave_summary_report:`leave-summary-report`,
resource_availability:`resource-availability`,
vlp_notifications:`notifications`,

// project ace
//   leave_application: 'leave-application',
//   timesheetCalender: 'time-sheets-calender',
//   taskProjectCategories: 'task-project-categories',
//   users_leave_details: `users-leave-details`,
//   get_time_sheet_values: `get-time-stamp-values`,
//   managerReview: `manager-review`,
//   add_on_leave_request: `add-on-leave-request`,
//   organization: `organization`,
//   userRole: `user-role`,
//   office_working_days: `office-working-days`,
//   profile_custom_user: `profile-custom-user`,
//   time_sheets: `timesheets`,
//   time_sheets_deadline_crossed: `time-sheets-deadline-crossed`,
//   time_sheets_monthly: `time-sheets-monthly`,
//   country_state_city: `country-state-city`,
//   people_list: `people`,
//   prefix_suffix: `prefix-suffix`,
//   center_list: `center`,
//   tag: `tag`,
//   master_leave_list: `master-leave-types`,
//   type_of_industries: `type-of-industries`,
//   main_category: `project-status-main-category`,
//   sub_category: `project-status-sub-category`,
//   project_tasks: `task-project-categories`,
//   project_list: `projects`,
//   org_department: `organization-department`,
//   approval_config: `time-sheets-approval-config`,
  notification: `get-notification`,
  update_notification: `update-seen-notification`,
//   timesheets:`timesheets`,
//   country:`country`,
//   state:`state`,
//   city:`city`,
//   client:`client`,
//   leave_master:`leave-master`,
//   employee_leaves:`employee_leaves`,
//   all_employee:`all-employee`,
//   apply_leave:`apply-leave`,
//   employee_leave_details:`employee-leave-details`,
//   project:`project`,
//   project_task:`project-task`,
//   task_hours:`timesheet-task-hours`,
//   update_timesheet_status:`update-timesheet-status`,
//   update_leave_details:`update-leave-details`,
//   allEmployee:`all-employee`,
//   working_hour:`working-hour`,
//   designation:`designation`,
//   department:`department`,
//   user:`user`,
//   holiday_calender:`upload-holiday-calender`,
//   project_template:`project_category`,
//   timesheet_comment:`timesheet-comment`,
//   leave_comment:`leave-comment`,
//   subscription_list:`subscription-list`,
//   buy_subscription:`buy-subscription`,
//   transaction_history:`transaction-history`,
//   configure_subscription:`configure-subscription`,
//   my_subscription:`my-subscription`,
//   cancel_my_subscription:`cancel-my-subscription`,
//   plan_types:`plan-types`,
//  working_hour_config: `super-admin-conf-working-hour`,
//  timesheet:`timesheet`,
//  timesheet_reports:`timesheet-reports`,
//  timesheet_summary:`timesheet-summary`,

};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
